### ISSUE TITLE
Language switcher links not working correctly

### ISSUE THREAD

**Issue by PrimozRome** [Wunderman-Thompson-Portugal/travelblog-multilingual#1]
I found one bug in this example, and I am not able to fix it. Maybe you can help?

Here is how to reproduce the bug on the deployed site:

1. Navigate to home page https://travelblog-multilingual.vercel.app
2. Open a blog post, for example: https://travelblog-multilingual.vercel.app/en/holidays/providence-three-days-later
3. Switch to Spanish version (or any other language). The correct blog post opens (https://travelblog-multilingual.vercel.app/es/vacaciones/providencia-tres-dias-despues).
4. Now open another blog post from the section "Más historias". For example this one https://travelblog-multilingual.vercel.app/es/viaje-familiar/solo-estamos-viviendo-en-un-mundo-inestable.
5. If you try to switch language to English (or any other language) the wrong blog article will open. In this case previously loaded blog post (https://travelblog-multilingual.vercel.app/en/holidays/providence-three-days-later). It should open this one right: https://travelblog-multilingual.vercel.app/family-travel/we-are-just-living-in-an-unstable-world.

Why is this happening?

Thanks,
Primoz

**Comment by alisonjsilva** [comment]
Can you check please?
It's fixed.
